import type { Metadata } from "next";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";


const bebas = Bebas_Neue({
  variable: "--font-bebas",
  subsets: ["latin"],
  weight: "400"
});



export const metadata: Metadata = {
  title: "Shop Vibe",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bebas.className}>
        {children}
      </body>
    </html>
  );
}
